[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "sLAwRJHIVI"
weight = 9_900

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "sLAwRJH2319"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "posts/projects"
identifier = "projects"
parent = "sLAwRJH2319"
weight = 10_000

[[footer]]
none = "none"
